/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFrameVotos;

/**
 *
 * @author familia4
 */
public class FormularioPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FormularioPrincipal
     */
    public FormularioPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        BusquedaVotos = new javax.swing.JButton();
        RegistroVotos = new javax.swing.JButton();
        ReporteVotos = new javax.swing.JButton();
        IngresarOtroUser = new javax.swing.JButton();
        ReporteArbol = new javax.swing.JToggleButton();
        BusquedaArbol = new javax.swing.JToggleButton();
        ReporteTablasHash = new javax.swing.JToggleButton();
        BusquedaTablasHash = new javax.swing.JToggleButton();
        EstadisticoBusquedaVotos = new javax.swing.JToggleButton();
        BusquedaGrafos = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(204, 0, 51));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("FORMULARIO PRINCIPAL");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jLabel2)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        BusquedaVotos.setBackground(new java.awt.Color(204, 0, 51));
        BusquedaVotos.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        BusquedaVotos.setForeground(new java.awt.Color(255, 255, 255));
        BusquedaVotos.setText("Formulario de Búsqueda de los Votos");
        BusquedaVotos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BusquedaVotosActionPerformed(evt);
            }
        });

        RegistroVotos.setBackground(new java.awt.Color(204, 0, 51));
        RegistroVotos.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        RegistroVotos.setForeground(new java.awt.Color(255, 255, 255));
        RegistroVotos.setText("Formulario Registro de Votos Faltantes");
        RegistroVotos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistroVotosActionPerformed(evt);
            }
        });

        ReporteVotos.setBackground(new java.awt.Color(204, 0, 51));
        ReporteVotos.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        ReporteVotos.setForeground(new java.awt.Color(255, 255, 255));
        ReporteVotos.setText("Formulario de Reportes de los Votos ");
        ReporteVotos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReporteVotosActionPerformed(evt);
            }
        });

        IngresarOtroUser.setBackground(new java.awt.Color(204, 0, 51));
        IngresarOtroUser.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        IngresarOtroUser.setForeground(new java.awt.Color(255, 255, 255));
        IngresarOtroUser.setText("Ingresar otro Usuario");
        IngresarOtroUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarOtroUserActionPerformed(evt);
            }
        });

        ReporteArbol.setBackground(new java.awt.Color(153, 0, 255));
        ReporteArbol.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        ReporteArbol.setForeground(new java.awt.Color(255, 255, 255));
        ReporteArbol.setText("Formulario de Reportes Arbol");
        ReporteArbol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReporteArbolActionPerformed(evt);
            }
        });

        BusquedaArbol.setBackground(new java.awt.Color(153, 0, 255));
        BusquedaArbol.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        BusquedaArbol.setForeground(new java.awt.Color(255, 255, 255));
        BusquedaArbol.setText("Formulario de Busqueda Arbol");
        BusquedaArbol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BusquedaArbolActionPerformed(evt);
            }
        });

        ReporteTablasHash.setBackground(new java.awt.Color(255, 102, 0));
        ReporteTablasHash.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        ReporteTablasHash.setForeground(new java.awt.Color(255, 255, 255));
        ReporteTablasHash.setText("Formulario de Reportes Tablas Hash");
        ReporteTablasHash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReporteTablasHashActionPerformed(evt);
            }
        });

        BusquedaTablasHash.setBackground(new java.awt.Color(255, 102, 0));
        BusquedaTablasHash.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        BusquedaTablasHash.setForeground(new java.awt.Color(255, 255, 255));
        BusquedaTablasHash.setText("Formulario de Busqueda Tablas Hash");
        BusquedaTablasHash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BusquedaTablasHashActionPerformed(evt);
            }
        });

        EstadisticoBusquedaVotos.setBackground(new java.awt.Color(0, 0, 204));
        EstadisticoBusquedaVotos.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        EstadisticoBusquedaVotos.setForeground(new java.awt.Color(255, 255, 255));
        EstadisticoBusquedaVotos.setText("Estadistico Busqueda Votos");
        EstadisticoBusquedaVotos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstadisticoBusquedaVotosActionPerformed(evt);
            }
        });

        BusquedaGrafos.setBackground(new java.awt.Color(0, 204, 102));
        BusquedaGrafos.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        BusquedaGrafos.setForeground(new java.awt.Color(255, 255, 255));
        BusquedaGrafos.setText("Formulario de Busqueda Grafos");
        BusquedaGrafos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BusquedaGrafosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ReporteVotos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RegistroVotos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BusquedaVotos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(IngresarOtroUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ReporteArbol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BusquedaArbol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ReporteTablasHash, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BusquedaTablasHash, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EstadisticoBusquedaVotos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BusquedaGrafos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(RegistroVotos)
                .addGap(18, 18, 18)
                .addComponent(BusquedaVotos)
                .addGap(18, 18, 18)
                .addComponent(ReporteVotos)
                .addGap(18, 18, 18)
                .addComponent(BusquedaTablasHash)
                .addGap(18, 18, 18)
                .addComponent(ReporteTablasHash)
                .addGap(18, 18, 18)
                .addComponent(EstadisticoBusquedaVotos)
                .addGap(18, 18, 18)
                .addComponent(BusquedaArbol)
                .addGap(18, 18, 18)
                .addComponent(ReporteArbol)
                .addGap(18, 18, 18)
                .addComponent(BusquedaGrafos)
                .addGap(18, 18, 18)
                .addComponent(IngresarOtroUser)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BusquedaVotosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BusquedaVotosActionPerformed

        // Crear una instancia del formulario secundario
        BusquedaVotos FormularioBusqueda = new BusquedaVotos();

        // Hacer visible el formulario secundario
        FormularioBusqueda.setVisible(true);
    }//GEN-LAST:event_BusquedaVotosActionPerformed

    private void RegistroVotosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistroVotosActionPerformed

        // Crear una instancia del formulario secundario
        RegistroVotos FormularioRegistro = new RegistroVotos();

        // Hacer visible el formulario secundario
        FormularioRegistro.setVisible(true);
    }//GEN-LAST:event_RegistroVotosActionPerformed

    private void ReporteVotosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReporteVotosActionPerformed

        // Crear una instancia del formulario secundario
        ReporteVotos FormularioReportes = new ReporteVotos();

        // Hacer visible el formulario secundario
        FormularioReportes.setVisible(true);
    }//GEN-LAST:event_ReporteVotosActionPerformed

    private void IngresarOtroUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarOtroUserActionPerformed

        // Cerrar el formulario secundario
        this.dispose();

        // Mostrar nuevamente el formulario principal (puedes crear una instancia si es necesario)
        LOGIN LOGIN = new LOGIN();
        LOGIN.setVisible(true);
    }//GEN-LAST:event_IngresarOtroUserActionPerformed

    private void ReporteArbolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReporteArbolActionPerformed

        // Crear una instancia del formulario secundario
        ReporteVotosArbol FormularioReportesArbol = new ReporteVotosArbol();

        // Hacer visible el formulario secundario
        FormularioReportesArbol.setVisible(true);
    }//GEN-LAST:event_ReporteArbolActionPerformed

    private void BusquedaArbolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BusquedaArbolActionPerformed

        // Crear una instancia del formulario secundario
        BusquedaVotosArbol FormularioBusquedaArbol = new BusquedaVotosArbol();

        // Hacer visible el formulario secundario
        FormularioBusquedaArbol.setVisible(true);
    }//GEN-LAST:event_BusquedaArbolActionPerformed

    private void ReporteTablasHashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReporteTablasHashActionPerformed

        // Crear una instancia del formulario secundario
        ReporteVotosTablasHash FormularioReportesTablasHash = new ReporteVotosTablasHash();

        // Hacer visible el formulario secundario
        FormularioReportesTablasHash.setVisible(true);
    }//GEN-LAST:event_ReporteTablasHashActionPerformed

    private void BusquedaTablasHashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BusquedaTablasHashActionPerformed

        // Crear una instancia del formulario secundario
        BusquedaTablasHash FormularioBusquedaTablasHash = new BusquedaTablasHash();

        // Hacer visible el formulario secundario
        FormularioBusquedaTablasHash.setVisible(true);
    }//GEN-LAST:event_BusquedaTablasHashActionPerformed

    private void EstadisticoBusquedaVotosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstadisticoBusquedaVotosActionPerformed

        // Crear una instancia del formulario secundario
        EstadisticoBusquedaVotos FormularioEstadisticoBusquedaVotos = new EstadisticoBusquedaVotos();

        // Hacer visible el formulario secundario
        FormularioEstadisticoBusquedaVotos.setVisible(true);
    }//GEN-LAST:event_EstadisticoBusquedaVotosActionPerformed

    private void BusquedaGrafosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BusquedaGrafosActionPerformed

        // Crear una instancia del formulario secundario
        BusquedaVotosGrafos FormularioBusquedaGrafos = new BusquedaVotosGrafos();

        // Hacer visible el formulario secundario
        FormularioBusquedaGrafos.setVisible(true);

    }//GEN-LAST:event_BusquedaGrafosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BusquedaArbol;
    private javax.swing.JToggleButton BusquedaGrafos;
    private javax.swing.JToggleButton BusquedaTablasHash;
    private javax.swing.JButton BusquedaVotos;
    private javax.swing.JToggleButton EstadisticoBusquedaVotos;
    private javax.swing.JButton IngresarOtroUser;
    private javax.swing.JButton RegistroVotos;
    private javax.swing.JToggleButton ReporteArbol;
    private javax.swing.JToggleButton ReporteTablasHash;
    private javax.swing.JButton ReporteVotos;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
